from graph_tool import load_graph
import os

from pycurv import TriangleGraph, calculate_curvedness
from pycurv import pycurv_io as io

"""
A script calculating VTK curvedness for each graph vertex from a GT file
generated by a curvature calculation workflow using PyCurv and writing a
VTP surface file containing this property.

Author: Maria Kalemanov (Max Planck Institute for Biochemistry)
"""

__author__ = 'kalemanov'

# Read in graph GT file
tg_file = '/fs/pool/pool-ruben/Maria/workspace/github/pycurv/' \
          'experimental_data_sets/ER/AVV/TCB_180830_l2_t2half.ER.AVV_rh10.gt'
tg = TriangleGraph()
tg.graph = load_graph(tg_file)
# Read in VTK principle curvatures for each vertex,
# calculate curvedness and add as a new property
tg.graph.vp.vtk_curvedness = tg.graph.new_vertex_property("float")
for v in tg.graph.vertices():
    v_vtk_kappa_1 = tg.graph.vp.max_curvature[v]
    v_vtk_kappa_2 = tg.graph.vp.min_curvature[v]
    v_vtk_curvedness = calculate_curvedness(v_vtk_kappa_1, v_vtk_kappa_2)
    tg.graph.vp.vtk_curvedness[v] = v_vtk_curvedness
# Transform the graph to surface and write to a VTP file
surf = tg.graph_to_triangle_poly(verbose=False)
surf_file = os.path.splitext(tg_file)[0] + "_VTKcurvedness.vtp"
io.save_vtp(surf, surf_file)
